=== rdabotelho/analyzer/source/src/com/rim/analyzer/resources/language-definition.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT analyzer (language-name|language-description|language-version|case-sensitive|computing-class|syntactic|lexical)*>

<!ELEMENT language-name (#PCDATA)>

<!ELEMENT language-description (#PCDATA)>

<!ELEMENT language-version (#PCDATA)>

<!ELEMENT case-sensitive (#PCDATA)>

<!ELEMENT computing-class (#PCDATA)>

<!ELEMENT lexical (tokens)>

<!ELEMENT tokens (comment|string|real|bool|integer|delimiter|arithmetic-operator|logical-operator|relational-operator|attribution-operator|identifier|key-words|custom-token)*>

<!ELEMENT custom-token (pattern)*>
<!ATTLIST custom-token
    end CDATA #IMPLIED
    begin CDATA #IMPLIED
    name CDATA #IMPLIED
    isComputed CDATA #IMPLIED
    isType CDATA #IMPLIED
  >

<!ELEMENT pattern (#PCDATA)>

<!ELEMENT key-words (pattern)*>
<!ATTLIST key-words
    name CDATA #IMPLIED
  >

<!ELEMENT identifier (pattern)*>
<!ATTLIST identifier
    name CDATA #IMPLIED
  >

<!ELEMENT arithmetic-operator (pattern)*>
<!ATTLIST arithmetic-operator
    name CDATA #IMPLIED
  >

<!ELEMENT logical-operator (pattern)*>
<!ATTLIST logical-operator
    name CDATA #IMPLIED
  >

<!ELEMENT relational-operator (pattern)*>
<!ATTLIST relational-operator
    name CDATA #IMPLIED
  >

<!ELEMENT attribution-operator (pattern)*>
<!ATTLIST attribution-operator
    name CDATA #IMPLIED
  >
      
<!ELEMENT delimiter (pattern)*>
<!ATTLIST delimiter
    name CDATA #IMPLIED
  >

<!ELEMENT integer (pattern)*>
<!ATTLIST integer
    name CDATA #IMPLIED
  >

<!ELEMENT real (pattern)*>
<!ATTLIST real
    name CDATA #IMPLIED
  >

<!ELEMENT bool (pattern)*>
<!ATTLIST bool
    name CDATA #IMPLIED
    trueValue CDATA #IMPLIED
    falseValue CDATA #IMPLIED
  >  
  
<!ELEMENT string (pattern)*>
<!ATTLIST string
    end CDATA #IMPLIED
    begin CDATA #IMPLIED
    name CDATA #IMPLIED
  >

<!ELEMENT comment (pattern)*>
<!ATTLIST comment
    end CDATA #IMPLIED
    begin CDATA #IMPLIED
    name CDATA #IMPLIED
  >

<!ELEMENT syntactic (context-free-grammar)>

<!ELEMENT context-free-grammar (not-terminal)>

<!ELEMENT not-terminal (#PCDATA|productions)*>
<!ATTLIST not-terminal
    name CDATA #IMPLIED
    method CDATA #IMPLIED
  >

<!ELEMENT productions (production)*>

<!ELEMENT production (terminal|not-terminal|empty)*>

<!ELEMENT terminal (#PCDATA)>
<!ATTLIST terminal
    name CDATA #IMPLIED
  >
  
<!ELEMENT empty (#PCDATA)>

=== rdabotelho/analyzer/source/src/com/rim/analyzer/resources/expression-definition.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE people_list SYSTEM "language-definition.dtd">
<analyzer>   

    <language-name>Expression</language-name>
    <language-description>Expression Language</language-description>
    <language-version>1.0</language-version>
    
    <computing-class>com.rim.analyzer.comp.ExpressionSupporter</computing-class>
        
    <lexical>
        <tokens>
            <real/>
            <integer/>
            <string/>
            <bool/>
            <logical-operator/>
            <relational-operator/>
            <arithmetic-operator/>
            <delimiter/>
        </tokens>
    </lexical>
    <syntactic>    
        
<!--

        <expression>		::= <expression> || <bool-term> | <bool-term>
       	<bool-term>		::= <bool-term> && <bool-not-factor> | <bool-not-factor>
       	<bool-not-factor>	::= ! <relation> | <relation>         
       	<relation>		::= <arith-expr> | <arith-expr> relational-operator <arith-expr>
	<arith-expr>		::= <arith-expr> + <term> | <arith-expr> - <term> | <term>
	<term>			::= <term> * <signed-factor> | <term> / <signed-factor> | <signed-factor>
       	<signed-factor>		::= + <factor> | - <factor> | <factor>
       	<factor>		::= ( <expression> ) | real | integer | string | bool
                                           
-->

        <context-free-grammar>

            <not-terminal name="expression" method="logicalOperation">                
                <productions>
                    <production>
                        <not-terminal name="expression"></not-terminal>
                        <terminal name="logical-operator">||</terminal>
                        <not-terminal name="bool-term"></not-terminal>
                    </production>
                    <production>
                        <not-terminal name="bool-term"></not-terminal>
                    </production>
                </productions>                                
            </not-terminal>

            <not-terminal name="bool-term">                
                <productions>
                    <production>
                        <not-terminal name="bool-term"></not-terminal>
                        <terminal name="logical-operator"><![CDATA[&&]]></terminal>
                        <not-terminal name="bool-not-factor"></not-terminal>
                    </production>
                    <production>
                        <not-terminal name="bool-not-factor"></not-terminal>
                    </production>
                </productions>                                                
            </not-terminal>
            
            <not-terminal name="bool-not-factor">
                <productions>
                    <production>
                        <terminal name="logical-operator">!</terminal>
                        <not-terminal name="relation"></not-terminal>
                    </production>
                    <production>
                        <not-terminal name="relation"></not-terminal>
                    </production>
                </productions>                                                                
            </not-terminal>
            
            <not-terminal name="relation" method="relationalOperation">                
                <productions>
                    <production>
                        <not-terminal name="arith-expr"></not-terminal>
                    </production>
                    <production>
                        <not-terminal name="arith-expr"></not-terminal>
                        <terminal name="relational-operator"></terminal>
                        <not-terminal name="arith-expr"></not-terminal>                        
                    </production>
                </productions>                                                                                
            </not-terminal>
            
            <not-terminal name="arith-expr" method="arithmeticOperation">                
                <productions>
                    <production>
                        <not-terminal name="arith-expr"></not-terminal>
                        <terminal name="arithmetic-operator">+</terminal>
                        <not-terminal name="term"></not-terminal>
                    </production>
                    <production>
                        <not-terminal name="arith-expr"></not-terminal>
                        <terminal name="arithmetic-operator">-</terminal>
                        <not-terminal name="term"></not-terminal>
                    </production>
                    <production>
                        <not-terminal name="term"></not-terminal>
                    </production>
                </productions>                                                                                                
            </not-terminal>
            
            <not-terminal name="term">                
                <productions>
                    <production>
                        <not-terminal name="term"></not-terminal>
                        <terminal name="arithmetic-operator">*</terminal>
                        <not-terminal name="signed-factor"></not-terminal>
                    </production>
                    <production>
                        <not-terminal name="term"></not-terminal>
                        <terminal name="arithmetic-operator">/</terminal>
                        <not-terminal name="signed-factor"></not-terminal>
                    </production>
                    <production>
                        <not-terminal name="signed-factor"></not-terminal>
                    </production>
                </productions>
            </not-terminal>
            
            <not-terminal name="signed-factor">                
                <productions>
                    <production>
                        <terminal name="arithmetic-operator">+</terminal>
                        <not-terminal name="factor"></not-terminal>
                    </production>
                    <production>
                        <terminal name="arithmetic-operator">-</terminal>
                        <not-terminal name="factor"></not-terminal>
                    </production>
                    <production>
                        <not-terminal name="factor"></not-terminal>
                    </production>
                </productions>
            </not-terminal>
            
            <not-terminal name="factor">                
                <productions>
                    <production>
                        <terminal name="delimiter">(</terminal>
                        <not-terminal name="expression"></not-terminal>
                        <terminal name="delimiter">)</terminal>
                    </production>
                    <production>
                        <terminal name="real"></terminal>
                    </production>
                    <production>
                        <terminal name="integer"></terminal>
                    </production>
                    <production>
                        <terminal name="string"></terminal>
                    </production>
                    <production>
                        <terminal name="bool"></terminal>
                    </production>
                </productions>                
            </not-terminal>            
            
        </context-free-grammar>        
    </syntactic>    
    
</analyzer>
